---
- name: JUNOS MODULE TO SET SYSTEM CONFIGS
  hosts: juniper
  gather_facts: no

  tasks:
    - name: GATHER FACTS
      junos_facts:
        gather_subset: min
        gather_network_resources: 'interfaces,l3_interfaces'
