---
- name: Start Stop Cisco CSRs
  hosts: localhost
  gather_facts: no

  vars:
    ec2_region: us-east-2
    target_environment:
      dev:
        - gdykeman-dev-network-student1-rtr1
        - subnet-0785c67615fdeeb0b
      prod:
        - gdykeman-prod-network-student1-rtr1
        - subnet-0da3f8a40fc0a0fb7

  tasks:
    - name: start CSRs
      ec2:
        region: "{{ec2_region}}"
        vpc_subnet_id: "{{item.value.1}}"
        instance_tags:
          Name: "{{item.value.0}}"
        state: running
      loop: "{{ target_environment | dict2items }}"
      tags:
        - start_csr

    - name: stop CSRs
      ec2:
        region: "{{ec2_region}}"
        vpc_subnet_id: "{{item.value.1}}"
        instance_tags:
          Name: "{{item.value.0}}"
        state: stopped
      loop: "{{ target_environment | dict2items }}"
      tags:
        - stop_csr