---
- name: gather facts
  ios_facts:

- name: ADD THE IOS BANNER
  ios_banner:
    text: "{{ network_banner }}"
    banner: login
    
- name: CONFIGURE THE MOTD
  ios_banner:
    banner: motd
    text: "{{ lookup('template', 'motd.j2') }}"
    state: present